### ISSUE TITLE
Course info page - Content realignment

### ISSUE THREAD

**Issue by LanderMuruaga** [exlskills/exlskills#33]
**Current situation**
Information crowded info page
https://exlskills.com/learn-en/courses/ap-computer-science-a-java-ap_java/info

**Solution**
Realign and format the content to make it easy to read/easy to understand

**Tasks**

Added by @svarlamov 

- [x] Update margins on markdown->html content

- [x] Add global max width constraints to course info page

![course-info-page](https://user-images.githubusercontent.com/41282864/44199361-2aa36700-a144-11e8-89de-9f3687eff548.png)

**Comment by svarlamov** [comment]
- [ ] Update margins on markdown->html content

- [ ] Add global max width constraints to course info page

**Comment by LanderMuruaga** [comment]
Some specs to help on front-end.
Basically it is a matter of adding some space in between blocks and changing the title sizes...
Top title: 36px
Section title: 20px

![course-info-page-specs](https://user-images.githubusercontent.com/41282864/44205499-e2da0b00-a156-11e8-8eaf-8ee6d5f1a8ac.png)

**Comment by svarlamov** [comment]
Done and in production, with minor changes in order to adhere to GitHub markdown standards. Also, some of the double-wide spacing needs to happen in the courseware itself. If you feel compelled to make those changes, you can start an issue/PR in the course-java-basics repo
