### ISSUE TITLE
Course overview page UI redesign

### ISSUE THREAD

**Issue by svarlamov** [exlskills/exlskills#60]
Major updates to the course overview page (incl lots of new mobile support)

**NOTE** Some aspects of the designs have not been finalized and various facets have already been changed since these were produced (such as the card navigation which has changed significantly). Also a lot of the wording in the GUI is still subject to change.

### Overview of updates

![image](https://user-images.githubusercontent.com/10859025/45401616-09bb2c80-b684-11e8-85d2-ec0380888c7f.png)

### Desktop

![image](https://user-images.githubusercontent.com/10859025/45401628-1475c180-b684-11e8-8695-747b50cb37a0.png)

![image](https://user-images.githubusercontent.com/10859025/45401631-1a6ba280-b684-11e8-9575-57595060df97.png)

![image](https://user-images.githubusercontent.com/10859025/45401636-235c7400-b684-11e8-853a-dc8f07b6be53.png)

![1 - course detail-b](https://user-images.githubusercontent.com/41282864/45485329-823eed80-b757-11e8-9ba2-ff3f6feacb57.png)

![4 - continue course](https://user-images.githubusercontent.com/41282864/45485364-a6023380-b757-11e8-8902-d3db90115915.png)

![2 - start course](https://user-images.githubusercontent.com/41282864/45485368-ac90ab00-b757-11e8-9566-7451a3762e16.png)

### Mobile

![image](https://user-images.githubusercontent.com/10859025/45401498-74b83380-b683-11e8-9198-ce5de81c347a.png)

![05-m-course-practice](https://user-images.githubusercontent.com/41282864/45486259-bbc52800-b75a-11e8-99d5-e7ff40f835fc.png)

![06-m-course-nav](https://user-images.githubusercontent.com/41282864/45486270-c7b0ea00-b75a-11e8-8da1-9b30ea3a7fd7.png)

![10-m-menu](https://user-images.githubusercontent.com/41282864/45486273-cbdd0780-b75a-11e8-9dde-049d6fd173b6.png)

@LanderMuruaga Are we planning to add more mobile designs here? I think that we should be able to infer from here, but your call if we need to point out certain things specifically.

### Todos

- [ ] Finalize designs

- [ ] Desktop course detail page (all progress states)

- [ ] Desktop course content (called program in designs...) page (all progress states)

- [ ] Mobile course detail page (all progress states)

- [ ] Mobile course content (called program in designs...) page (all progress states)

**Comment by LanderMuruaga** [comment]
Added Practice and Navigation from Q&A to course detail. 
Elements to notice. 
1. Dropdow (not necessary but helpful). We can avoid it or implement later if necessary.
2. Top header Back Arrow to move back from Questions/Practice to Course detail

**Comment by LanderMuruaga** [comment]
Adding some updated content for mobile...

NOTE: The "Menu" below the header, shows navigation into the course. It is actually the same content than the Left sidebar on desktop. (!) The exception will be the course doing/learning screens that will be without menu to focus on doing it (similar to shopping cart screens that are clean to avoid distractions). 

1. **Course detail page**: Specs section will be nice to have the close/open functionality. 
2. **Course (Learn/Practice)**: As said in the note previously, on this page is better to have a clean/task focused page. (!) If the dropdown on title to view course unit/sections is complex to implement, we can avoid it. 
3. **Course content page**: Modified chart colors to make it more clean and vibrant. Instructor and Certificate banners are provisional.
4. **Certificate page**: The "How to become a certified professional" graphic or content is TBD. The idea is to show the process briefly with some dots in a nice way. We can add it later, both in mobile and desk.
5. **Progress page**: I know is missing. The content is fine. Just some aesthetic improvements and future plans to talk about. Working on it.

**Question:/improvement** 
@svarlamov is it possible to add a intermediate screen when a user finishes a unit? Some ind of Congratulations page (with a motivationa intentionl) with a fast message in a lightbox or as a notification sliding in and out right to left. It helps to have a control of where you are and how are you doing and keeps users motivated in that sense. I would like to understand what kind of options do we have in that sense (making it easy) or even if it is possible.

![m-03-course detail](https://user-images.githubusercontent.com/41282864/45580780-56c21d00-b895-11e8-8b85-e497faf844b2.png)
![m-04-learn course](https://user-images.githubusercontent.com/41282864/45580787-6a6d8380-b895-11e8-8976-25131b8886e1.png)
![m-04a-course-nav](https://user-images.githubusercontent.com/41282864/45580790-70fbfb00-b895-11e8-9318-2f9fa43f88d6.png)
![m-04b-practice course](https://user-images.githubusercontent.com/41282864/45580800-90932380-b895-11e8-9575-2c5ef22dce26.png)
![m-05-course content](https://user-images.githubusercontent.com/41282864/45580801-912bba00-b895-11e8-8736-45ba1fabab4e.png)
![m-07-certificate](https://user-images.githubusercontent.com/41282864/45580802-912bba00-b895-11e8-81b1-fff02c24800f.png)
![07-certificate](https://user-images.githubusercontent.com/41282864/45581177-e8cc2480-b899-11e8-9bb0-f528b4e65adc.png)

**Comment by LanderMuruaga** [comment]
@andyluu1908  Adding Course details for Dark theme. 
Please, let me know if you need any specific screens/piece in order to prioritize them. Thanks.

![d-03 - course detail](https://user-images.githubusercontent.com/41282864/45695301-6aa1a380-bb61-11e8-8c94-945969143165.png)
![d-04 - learn course](https://user-images.githubusercontent.com/41282864/45695302-6aa1a380-bb61-11e8-903f-ba293a56c829.png)

**Comment by LanderMuruaga** [comment]
Adding course pages for Dark theme... 

![d-05 - course content](https://user-images.githubusercontent.com/41282864/45766427-d5251300-bc37-11e8-8cf6-6a53b6e18092.png)
![d-06-progress](https://user-images.githubusercontent.com/41282864/45766313-88413c80-bc37-11e8-9cc4-44ed779b4f7b.png)

**Comment by LanderMuruaga** [comment]
IMPORTANT:
Discussion and updates to this issue have been moved to Issue https://github.com/exlskills/exlskills/issues/75
